feature/AAT-39-Product-Information-Section : implement add product section 1
hardikt093/angular-ecommerce-theme pull request #14
Opened 2023-03-31 13:04 UTC by chintan-albiorix

…ction 1

2023-04-11 10:51 UTC, Malay23al requested changes

2023-04-11 10:51 UTC, Malay23al commented on backend/src/app/layouts/layouts.component.html
> +<div class="d-flex position-relative">
Do we need "position-relative" class here?

2023-04-11 10:51 UTC, Malay23al commented on backend/src/app/pages/products/products.module.ts
> +    CommonModule,
Do we need "CommonModule" here?
We already imported "CommonModule" in page module file.

2023-04-11 10:51 UTC, Malay23al commented on backend/src/app/pages/products/products.module.ts
> +    SharedModule,
How many places we imported "SharedModule"?
Do we need to import on child module?

2023-04-11 10:51 UTC, Malay23al commented on backend/src/assets/scss/_utilities.scss
> +    ),
What is the use of this code?

2023-04-11 10:51 UTC, Malay23al commented on backend/src/app/app.module.ts
> +    BrowserAnimationsModule
What is the use of "BrowserAnimationsModule"?

2023-04-11 10:51 UTC, Malay23al commented on backend/src/assets/scss/custom/_custom.scss
We never have to create custom scss file.

2023-04-11 10:51 UTC, Malay23al commented on backend/src/assets/scss/custom/_custom.scss
> +.tag-chips-height {
Use name "mat-chip-height-auto"

2023-04-11 11:05 UTC, chintan-albiorix commented on backend/src/assets/scss/_utilities.scss
> +    ),
For applying font-size:10px in label

2023-04-11 11:46 UTC, chintan-albiorix commented on backend/src/app/pages/products/products.module.ts
> +    CommonModule,
products.module is lazily loaded so it will not get it's parents dependencies.

2023-04-11 13:27 UTC, Malay23al requested changes

2023-04-11 13:27 UTC, Malay23al commented on backend/src/app/pages/pages.module.ts
>    ],
Remove unnecessary code

2023-04-11 13:27 UTC, Malay23al commented on backend/src/assets/scss/_utilities.scss
> +    ),
Can we follow one method?
In _helper.scss we used different method.

2023-04-13 09:56 UTC, Malay23al requested changes

2023-04-13 09:56 UTC, Malay23al commented on backend/src/assets/scss/app.scss
> +@include mat.all-component-themes($backend-theme);
We need to check how we can use our color in mat theming.

2023-04-13 09:56 UTC, Malay23al commented on backend/src/app/pages/products/add-product-v1/add-product-v1.component.html
> +                <h6 class="mb-0 text-white fs-18">Product Information</h6>
This should be h3

2023-04-13 09:56 UTC, Malay23al commented on backend/src/app/pages/products/add-product-v1/add-product-v1.component.html
> +                        <label for="productTitle" class="form-label mb-1 lh-sm">Product Title</label>
Check if all label has same margin then we can modify form-label margin.
form-label class used to add bottom margin

2023-04-13 09:56 UTC, Malay23al commented on backend/src/app/pages/products/add-product-v1/add-product-v1.component.html
> +                        <label for="tags" class="form-label lh-sm mb-1">Tags
What is the use of "for" here?

2023-04-13 09:56 UTC, Malay23al commented on backend/src/app/pages/products/add-product-v1/add-product-v1.component.html
> +                        <mat-chip-list #chipGrid class="form-control border-0 shadow-light m-0 px-2">
What is the use of "m-0" here?

2023-04-13 09:56 UTC, Malay23al commented on backend/src/app/pages/products/add-product-v1/add-product-v1.component.ts
> +  add(event: MatChipInputEvent): void {
Change function to "addTag" and "removeTag"

2023-04-13 11:17 UTC, chintan-albiorix commented on backend/src/app/pages/products/add-product-v1/add-product-v1.component.html
> +                            <input class="form-control border-0 shadow-none py-0" placeholder="Enter new tags..."
To remove focus in input on click.

2023-04-14 10:53 UTC, Malay23al approved these changes

2023-04-17 06:54 UTC, merged