feature/AAT-8: Create structure of Sidebar and implement sidebar desi…
hardikt093/angular-ecommerce-theme pull request #5
Opened 2023-03-10 12:42 UTC by chintan-albiorix

…gn in Admin Panel

2023-03-14 15:06 UTC, Malay23al requested changes

2023-03-14 15:06 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +        width: $sidebar-expand-width;
Directly use width

2023-03-14 15:06 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +            width: $sidebar-expand-width;
Directly use width

2023-03-14 15:06 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +        width: $sidebar-collapse-width;
Directly use width

2023-03-14 15:06 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +    .sidebar-collapse {
sass nesting

2023-03-14 15:06 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +    }
Can you please explain this css?

2023-03-14 15:06 UTC, Malay23al commented on backend/src/app/layouts/sidebar/sidebar.component.html
> +            <ng-container *ngFor="let item of menuItems">
Use proper name instead of item

2023-03-14 15:06 UTC, Malay23al commented on backend/src/app/layouts/sidebar/sidebar.component.html
> +                    <a href='#' class="nav-link link-secondary px-10" [routerLink]="item?.url">
What is the use of href and routerLink?

2023-03-31 09:36 UTC, Malay23al requested changes

2023-03-31 09:36 UTC, Malay23al commented on backend/src/app/core/constants/menu.ts
Can we remove id dependency?

2023-03-31 12:05 UTC, Malay23al requested changes
Design not match when sidebar collapse
![image](https://user-images.githubusercontent.com/126240448/229115335-d9a7dfe2-dfcc-4aaf-8129-67e9bed14e63.png)

2023-03-31 14:37 UTC, Malay23al requested changes
We need to improve expand/collapse visualisation
Ex. https://preview.keenthemes.com/metronic8/angular/demo1/dashboard

2023-04-04 08:48 UTC, Malay23al requested changes

2023-04-04 08:48 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_header.scss
>  }
If header-wrapper is parent of logo-container then follow nested hierarchy

2023-04-04 08:48 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
Format this file

2023-04-04 12:27 UTC, Malay23al requested changes

2023-04-04 12:27 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +                overflow: hidden;
Do we need this two property?

2023-04-04 12:27 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +        overflow-y: auto !important;
Same css is copy pasted in "sidebar-collapse".
There is only change of width.

2023-04-04 12:27 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +                flex: 1 0 100%;
Same thing happen here also

2023-04-04 12:27 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +                }
Merge this css

2023-04-04 12:27 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +            }
Merge this also

2023-04-04 12:27 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +                align-items: center;
Use class if we are not updating in hover/active mode

2023-04-05 11:19 UTC, Malay23al requested changes

2023-04-06 09:46 UTC, Malay23al requested changes

2023-04-06 09:46 UTC, Malay23al commented on backend/src/app/layouts/common/menu-item/menu-item.component.html
> +        <a class="nav-link d-flex align-items-center overflow-hidden rounded-0 link-secondary p-10 ps-2"
Do we need "overflow-hidden" and "rounded-0" here?
What is the use of "ps-2" here?

2023-04-06 09:46 UTC, Malay23al commented on backend/src/app/layouts/common/menu-item/menu-item.component.html
> +        <button class="nav-link d-flex align-items-center overflow-hidden rounded-0 link-secondary p-10 ps-2"
Do we need "overflow-hidden" here?
What is the use of "ps-2" here?

2023-04-06 09:46 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +        z-index: 1000;
Add this property to default.

2023-04-06 09:46 UTC, Malay23al commented on backend/src/assets/scss/custom/components/_sidebar.scss
> +            cursor: pointer;
Why we need "cursor: pointer;" in a tag?

2023-04-06 09:58 UTC, chintan-albiorix commented on backend/src/app/layouts/common/menu-item/menu-item.component.html
> +        <a class="nav-link d-flex align-items-center overflow-hidden rounded-0 link-secondary p-10 ps-2"
For hide overflow-x scroll
border-left taking 3 px space so in collapse sidebar icon is not centered aligned

2023-04-06 09:59 UTC, chintan-albiorix commented on backend/src/app/layouts/common/menu-item/menu-item.component.html
> +        <button class="nav-link d-flex align-items-center overflow-hidden rounded-0 link-secondary p-10 ps-2"
For hide overflow-x scroll
border-left taking 3 px space so in collapse sidebar icon is not centered aligned

2023-04-06 12:16 UTC, Malay23al approved these changes

2023-04-06 12:17 UTC, merged